language: bash
services: docker

env:
  - VERSION=4.0.0 VARIANT=ubuntu-12.04 DockerFile_DIR=ubuntu/12.04/4/4.0.0
  - VERSION=4.0.0 VARIANT=ubuntu-14.04 DockerFile_DIR=ubuntu/14.04/4/4.0.0
  - VERSION=4.0.0 VARIANT=ubuntu-16.04 DockerFile_DIR=ubuntu/16.04/4/4.0.0
  - VERSION=4.0.1 VARIANT=ubuntu-12.04 DockerFile_DIR=ubuntu/12.04/4/4.0.1
  - VERSION=4.0.1 VARIANT=ubuntu-14.04 DockerFile_DIR=ubuntu/14.04/4/4.0.1
  - VERSION=4.0.1 VARIANT=ubuntu-16.04 DockerFile_DIR=ubuntu/16.04/4/4.0.1


install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$DockerFile_DIR"
  - image="pdns:${VERSION}${VARIANT:+-$VARIANT}"

script:
  - docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
- docker images
